version: '3.9'

services:
    api:
        build: ./api
        volumes:
            - ./api:/app
            - /app/node_modules
        depends_on:
            - database
            - database-test
        ports:
            - 4040:4000
        environment:
            MONGO_URI: mongodb://database:27017/wild-app-alternance
            MONGO_URI_TEST: mongodb://database:27017/wild-app-alternance-test

    client:
        build: ./client
        ports:
            - 8080:3000
        depends_on:
            - api
        volumes:
            - ./client:/app
            - /app/node_modules

    database:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./data:/data/db

    database-test:
        image: mongo
        ports:
            - 27018:27018
        restart: always
